'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/G0t9Fcu65Tn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function InputForm() {
  return (
    <div className="mx-auto max-w-md space-y-6 py-12">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Upload Document</h1>
        <p className="text-gray-500 dark:text-gray-400">Fill out the form below to upload your .docx file.</p>
      </div>

      <form
        className="space-y-4"
        onSubmit={(e) => {
          e.preventDefault()
          alert('Submitted!')
        }}
      >
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="first-name">First Name</Label>
            <Input id="first-name" placeholder="John" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last-name">Last Name</Label>
            <Input id="last-name" placeholder="Doe" required />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="phone">Phone Number</Label>
          <Input id="phone" pattern="[0-9]{10}" placeholder="1234567890" required type="tel" />
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Please enter your phone number in the format 1234567890.
          </p>
        </div>
        <div className="space-y-2">
          <Label htmlFor="file">Upload Document</Label>
          <Input accept=".docx" id="file" required type="file" />
          <p className="text-sm text-gray-500 dark:text-gray-400">Please upload a .docx file.</p>
        </div>
        <Button className="w-full" type="submit">
          Upload
        </Button>
      </form>
    </div>
  )
}
